import { PiecesBoardPositions, Side } from './Types';

export const BOARD_SIZE = 8;

export const PIECES_START_POSITION: PiecesBoardPositions = {
  A1: { name: 'Rook', side: Side.WHITE },
  B1: { name: 'Knight', side: Side.WHITE },
  C1: { name: 'Bishop', side: Side.WHITE },
  D1: { name: 'Queen', side: Side.WHITE },
  E1: { name: 'King', side: Side.WHITE },
  F1: { name: 'Bishop', side: Side.WHITE },
  G1: { name: 'Knight', side: Side.WHITE },
  H1: { name: 'Rook', side: Side.WHITE },
  A2: { name: 'Pawn', side: Side.WHITE },
  B2: { name: 'Pawn', side: Side.WHITE },
  C2: { name: 'Pawn', side: Side.WHITE },
  D2: { name: 'Pawn', side: Side.WHITE },
  E2: { name: 'Pawn', side: Side.WHITE },
  F2: { name: 'Pawn', side: Side.WHITE },
  G2: { name: 'Pawn', side: Side.WHITE },
  H2: { name: 'Pawn', side: Side.WHITE },
  A8: { name: 'Rook', side: Side.BLACK },
  B8: { name: 'Knight', side: Side.BLACK },
  C8: { name: 'Bishop', side: Side.BLACK },
  D8: { name: 'Queen', side: Side.BLACK },
  E8: { name: 'King', side: Side.BLACK },
  F8: { name: 'Bishop', side: Side.BLACK },
  G8: { name: 'Knight', side: Side.BLACK },
  H8: { name: 'Rook', side: Side.BLACK },
  A7: { name: 'Pawn', side: Side.BLACK },
  B7: { name: 'Pawn', side: Side.BLACK },
  C7: { name: 'Pawn', side: Side.BLACK },
  D7: { name: 'Pawn', side: Side.BLACK },
  E7: { name: 'Pawn', side: Side.BLACK },
  F7: { name: 'Pawn', side: Side.BLACK },
  G7: { name: 'Pawn', side: Side.BLACK },
  H7: { name: 'Pawn', side: Side.BLACK },
};
